name: Daily Commit

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create a commit - 24f3001410@ds.study.iitm.ac.in
        run: |
          echo "Commit for $(date)" >> index.txt
          git add index.txt
          git commit -m "Automated daily commit"
          git push
